CREATE SCHEMA ds;


CREATE TABLE IF NOT EXISTS ds.ft_balance_f (
	on_date DATE NOT NULL,
	account_rk NUMERIC NOT NULL,
	currency_rk NUMERIC,
	balance_out FLOAT,
	CONSTRAINT ds_ft_balance_f_pk PRIMARY KEY (on_date, account_rk)
);

CREATE TABLE IF NOT EXISTS ds.ft_posting_f (
	oper_date DATE NOT NULL, 
	credit_account_rk NUMERIC NOT NULL,
	debet_account_rk NUMERIC NOT NULL,
	credit_amount FLOAT,
	debet_amount FLOAT
);

CREATE TABLE IF NOT EXISTS ds.md_account_d (
	data_actual_date DATE NOT NULL,
	data_actual_end_date DATE NOT NULL,
	account_rk NUMERIC NOT NULL, 
	account_number VARCHAR(20) NOT NULL,
	char_type VARCHAR(1) NOT NULL,
	currency_rk NUMERIC NOT NULL, 
	currency_code VARCHAR(3) NOT NULL,
	CONSTRAINT ds_md_account_d_pk PRIMARY KEY (data_actual_date, account_rk)
);

CREATE TABLE IF NOT EXISTS ds.md_currency_d (
	currency_rk NUMERIC NOT NULL,
	data_actual_date DATE NOT NULL,
	data_actual_end_date DATE,
	currency_code VARCHAR(3),
	code_iso_char VARCHAR(3),
	CONSTRAINT ds_md_currency_d_pk PRIMARY KEY (currency_rk, data_actual_date)
);

CREATE TABLE IF NOT EXISTS ds.md_exchange_rate_d (
	data_actual_date DATE NOT NULL,
	data_actual_end_date DATE,
	currency_rk NUMERIC NOT NULL, 
	reduced_cource FLOAT,
	code_iso_num VARCHAR(3),
	CONSTRAINT ds_md_exchange_rate_d_pk PRIMARY KEY (data_actual_date, currency_rk)
);

CREATE TABLE IF NOT EXISTS ds.md_ledger_account_s (
	chapter CHAR(1), 
	chapter_name VARCHAR(16),
	section_number INTEGER, 
	section_name VARCHAR(22),
	subsection_name VARCHAR(21),
	ledger1_account INTEGER,
	ledger1_account_name VARCHAR(47),
	ledger_account INTEGER NOT NULL,
	ledger_account_name VARCHAR(153),
	characteristic CHAR(1),
	is_resident INTEGER,
	is_reserve INTEGER,
	is_reserved INTEGER,
	is_loan INTEGER,
	is_reserved_assets INTEGER,
	is_overdue INTEGER,
	is_interest INTEGER,
	pair_account VARCHAR(5),
	start_date DATE NOT NULL,
	end_date DATE,
	is_rub_only INTEGER,
	min_term VARCHAR(1),
	min_term_measure VARCHAR(1),
	max_term VARCHAR(1),
	max_term_measure VARCHAR(1),
	ledger_acc_full_name_translit VARCHAR(1),
	is_revaluation VARCHAR(1),
	is_correct VARCHAR(1),
	CONSTRAINT ds_md_ledger_account_s_pk PRIMARY KEY (ledger_account, start_date)
);


CREATE SCHEMA logs;

CREATE TABLE IF NOT EXISTS logs.logs_table (
	log_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	log_start_time TIMESTAMPTZ NOT NULL,
	log_end_time TIMESTAMPTZ NOT NULL,
	log_message TEXT NOT NULL,
	log_err_code TEXT,
	log_err_msg TEXT
  );
 
-- SELECT * FROM logs.logs_table;

 /*
SELECT * FROM ds.ft_balance_f;
SELECT * FROM ds.ft_posting_f;
SELECT * FROM ds.md_account_d;
SELECT * FROM ds.md_currency_d;
SELECT * FROM ds.md_exchange_rate_d;
SELECT * FROM ds.md_ledger_account_s;
 */

 /*
TRUNCATE ds.ft_balance_f;
TRUNCATE ds.ft_posting_f;
TRUNCATE ds.md_account_d;
TRUNCATE ds.md_currency_d;
TRUNCATE ds.md_exchange_rate_d;
TRUNCATE ds.md_ledger_account_s;
 */